### ISSUE TITLE
Build fails on amd64

### ISSUE THREAD

**Issue by BelegCuthalion** [15-317/tutch#1]
`make slmnj` on Debian on amd64 fails with error
```
mv: cannot stat 'src/tutch-heapimg.amd64-linux': No such file or directory
Makefile:13: recipe for target 'smlnj' failed
make: *** [smlnj] Error 1
```

Although this then creates  a `tutch-heapimg.x86-linux` in `src`, which I then renamed to `tutch-heapimg.amd64-linux` and next build passed without error. Don't know if it is a real fix.

**Comment by kcrary** [comment]
I've checked in a new Makefile, but I don't have that architecture so I can't test it. Could you please check out branch "32-bit" and run "make 32+smlnj"?

**Comment by BelegCuthalion** [comment]
@kcrary yes it passes successfully.

**Comment by kcrary** [comment]
Okay, it's merged.
